// <auto-generated />
using System;
using LibraryManagementClassLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementClassLib.Migrations
{
    [DbContext(typeof(LibraryManagementAPIDbContext))]
    [Migration("20260125134817_BorrowRequestEntity")]
    partial class BorrowRequestEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "AuthorsId");

                    b.HasIndex("AuthorsId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            AuthorsId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            AuthorsId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            AuthorsId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            AuthorsId = 4
                        },
                        new
                        {
                            BooksId = 5,
                            AuthorsId = 5
                        },
                        new
                        {
                            BooksId = 6,
                            AuthorsId = 6
                        },
                        new
                        {
                            BooksId = 7,
                            AuthorsId = 7
                        },
                        new
                        {
                            BooksId = 8,
                            AuthorsId = 8
                        },
                        new
                        {
                            BooksId = 9,
                            AuthorsId = 9
                        },
                        new
                        {
                            BooksId = 10,
                            AuthorsId = 10
                        });
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 3
                        },
                        new
                        {
                            BooksId = 2,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 4,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 4,
                            CategoriesId = 6
                        },
                        new
                        {
                            BooksId = 5,
                            CategoriesId = 4
                        },
                        new
                        {
                            BooksId = 5,
                            CategoriesId = 10
                        },
                        new
                        {
                            BooksId = 6,
                            CategoriesId = 4
                        },
                        new
                        {
                            BooksId = 7,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 7,
                            CategoriesId = 5
                        },
                        new
                        {
                            BooksId = 8,
                            CategoriesId = 5
                        },
                        new
                        {
                            BooksId = 9,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 10,
                            CategoriesId = 1
                        });
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ernest",
                            LastName = "Hemingway"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Gabriel",
                            LastName = "García Márquez"
                        });
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableCopies = 8,
                            ISBN = "978-0451524935",
                            PublisherId = 1,
                            Title = "1984",
                            TotalCopies = 10
                        },
                        new
                        {
                            Id = 2,
                            AvailableCopies = 6,
                            ISBN = "978-0446310789",
                            PublisherId = 2,
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 8
                        },
                        new
                        {
                            Id = 3,
                            AvailableCopies = 10,
                            ISBN = "978-0743273565",
                            PublisherId = 3,
                            Title = "The Great Gatsby",
                            TotalCopies = 12
                        },
                        new
                        {
                            Id = 4,
                            AvailableCopies = 12,
                            ISBN = "978-1503290563",
                            PublisherId = 4,
                            Title = "Pride and Prejudice",
                            TotalCopies = 15
                        },
                        new
                        {
                            Id = 5,
                            AvailableCopies = 15,
                            ISBN = "978-0439708180",
                            PublisherId = 5,
                            Title = "Harry Potter and the Sorcerer's Stone",
                            TotalCopies = 20
                        },
                        new
                        {
                            Id = 6,
                            AvailableCopies = 7,
                            ISBN = "978-0547928227",
                            PublisherId = 1,
                            Title = "The Hobbit",
                            TotalCopies = 10
                        },
                        new
                        {
                            Id = 7,
                            AvailableCopies = 5,
                            ISBN = "978-0307743657",
                            PublisherId = 2,
                            Title = "The Shining",
                            TotalCopies = 8
                        },
                        new
                        {
                            Id = 8,
                            AvailableCopies = 4,
                            ISBN = "978-0062073501",
                            PublisherId = 3,
                            Title = "Murder on the Orient Express",
                            TotalCopies = 6
                        },
                        new
                        {
                            Id = 9,
                            AvailableCopies = 6,
                            ISBN = "978-0684801223",
                            PublisherId = 4,
                            Title = "The Old Man and the Sea",
                            TotalCopies = 7
                        },
                        new
                        {
                            Id = 10,
                            AvailableCopies = 7,
                            ISBN = "978-0060883287",
                            PublisherId = 5,
                            Title = "One Hundred Years of Solitude",
                            TotalCopies = 9
                        });
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.BookIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookIssues");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.BorrowRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRequests");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "History"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Children"
                        });
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("BookIssueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookIssueId")
                        .IsUnique();

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1745 Broadway, New York, NY 10019",
                            Name = "Penguin Random House"
                        },
                        new
                        {
                            Id = 2,
                            Address = "195 Broadway, New York, NY 10007",
                            Name = "HarperCollins"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1230 Avenue of the Americas, New York, NY 10020",
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 4,
                            Address = "120 Broadway, New York, NY 10271",
                            Name = "Macmillan Publishers"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1290 Avenue of the Americas, New York, NY 10104",
                            Name = "Hachette Book Group"
                        });
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementClassLib.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementClassLib.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.BookIssue", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.Book", "Book")
                        .WithMany("BookIssues")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementClassLib.Entities.User", "User")
                        .WithMany("BookIssues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.BorrowRequest", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.Book", "Book")
                        .WithMany("BookRequests")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementClassLib.Entities.User", "User")
                        .WithMany("BookRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Fine", b =>
                {
                    b.HasOne("LibraryManagementClassLib.Entities.BookIssue", "BookIssue")
                        .WithOne("Fine")
                        .HasForeignKey("LibraryManagementClassLib.Entities.Fine", "BookIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookIssue");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Book", b =>
                {
                    b.Navigation("BookIssues");

                    b.Navigation("BookRequests");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.BookIssue", b =>
                {
                    b.Navigation("Fine")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementClassLib.Entities.User", b =>
                {
                    b.Navigation("BookIssues");

                    b.Navigation("BookRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
